// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nftmngr/display_option.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DisplayOption struct {
	BoolTrueValue  string                `protobuf:"bytes,1,opt,name=bool_true_value,json=boolTrueValue,proto3" json:"bool_true_value,omitempty"`
	BoolFalseValue string                `protobuf:"bytes,2,opt,name=bool_false_value,json=boolFalseValue,proto3" json:"bool_false_value,omitempty"`
	Opensea        *OpenseaDisplayOption `protobuf:"bytes,3,opt,name=opensea,proto3" json:"opensea,omitempty"`
}

func (m *DisplayOption) Reset()         { *m = DisplayOption{} }
func (m *DisplayOption) String() string { return proto.CompactTextString(m) }
func (*DisplayOption) ProtoMessage()    {}
func (*DisplayOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_38983a60548f9882, []int{0}
}
func (m *DisplayOption) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DisplayOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DisplayOption.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DisplayOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisplayOption.Merge(m, src)
}
func (m *DisplayOption) XXX_Size() int {
	return m.Size()
}
func (m *DisplayOption) XXX_DiscardUnknown() {
	xxx_messageInfo_DisplayOption.DiscardUnknown(m)
}

var xxx_messageInfo_DisplayOption proto.InternalMessageInfo

func (m *DisplayOption) GetBoolTrueValue() string {
	if m != nil {
		return m.BoolTrueValue
	}
	return ""
}

func (m *DisplayOption) GetBoolFalseValue() string {
	if m != nil {
		return m.BoolFalseValue
	}
	return ""
}

func (m *DisplayOption) GetOpensea() *OpenseaDisplayOption {
	if m != nil {
		return m.Opensea
	}
	return nil
}

func init() {
	// proto.RegisterType((*DisplayOption)(nil), "thesixnetwork.sixnft.nftmngr.DisplayOption")
}

func init() { proto.RegisterFile("nftmngr/display_option.proto", fileDescriptor_38983a60548f9882) }

var fileDescriptor_38983a60548f9882 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xc9, 0x4b, 0x2b, 0xc9,
	0xcd, 0x4b, 0x2f, 0xd2, 0x4f, 0xc9, 0x2c, 0x2e, 0xc8, 0x49, 0xac, 0x8c, 0xcf, 0x2f, 0x28, 0xc9,
	0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x29, 0xc9, 0x48, 0x2d, 0xce, 0xac,
	0xc8, 0x4b, 0x2d, 0x29, 0xcf, 0x2f, 0xca, 0xd6, 0x03, 0x31, 0xd3, 0x4a, 0xf4, 0xa0, 0x5a, 0xa4,
	0x54, 0x60, 0x7a, 0xf3, 0x0b, 0x52, 0xf3, 0x8a, 0x53, 0x13, 0xe3, 0xb1, 0x99, 0xa1, 0xb4, 0x9e,
	0x91, 0x8b, 0xd7, 0x05, 0x22, 0xe1, 0x0f, 0x16, 0x17, 0x52, 0xe3, 0xe2, 0x4f, 0xca, 0xcf, 0xcf,
	0x89, 0x2f, 0x29, 0x2a, 0x4d, 0x8d, 0x2f, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0xe2, 0x05, 0x09, 0x87, 0x14, 0x95, 0xa6, 0x86, 0x81, 0x04, 0x85, 0x34, 0xb8, 0x04,
	0xc0, 0xea, 0xd2, 0x12, 0x73, 0x8a, 0x61, 0x0a, 0x99, 0xc0, 0x0a, 0xf9, 0x40, 0xe2, 0x6e, 0x20,
	0x61, 0x88, 0x4a, 0x1f, 0x2e, 0x76, 0xa8, 0x1b, 0x24, 0x98, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0x8c,
	0xf4, 0xf0, 0xb9, 0x5c, 0xcf, 0x1f, 0xa2, 0x18, 0xc5, 0x59, 0x41, 0x30, 0x23, 0x9c, 0x3c, 0x4f,
	0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18,
	0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21, 0x4a, 0x3f, 0x3d, 0xb3, 0x24, 0xa3, 0x34,
	0x49, 0x2f, 0x39, 0x3f, 0x57, 0x1f, 0xc5, 0x02, 0x7d, 0x88, 0x05, 0xfa, 0x15, 0xfa, 0xb0, 0x30,
	0x29, 0xa9, 0x2c, 0x48, 0x2d, 0x4e, 0x62, 0x03, 0x87, 0x81, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0xb9, 0x3b, 0x08, 0xc6, 0x67, 0x01, 0x00, 0x00,
}

func (m *DisplayOption) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DisplayOption) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DisplayOption) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Opensea != nil {
		{
			size, err := m.Opensea.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDisplayOption(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BoolFalseValue) > 0 {
		i -= len(m.BoolFalseValue)
		copy(dAtA[i:], m.BoolFalseValue)
		i = encodeVarintDisplayOption(dAtA, i, uint64(len(m.BoolFalseValue)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BoolTrueValue) > 0 {
		i -= len(m.BoolTrueValue)
		copy(dAtA[i:], m.BoolTrueValue)
		i = encodeVarintDisplayOption(dAtA, i, uint64(len(m.BoolTrueValue)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDisplayOption(dAtA []byte, offset int, v uint64) int {
	offset -= sovDisplayOption(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DisplayOption) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BoolTrueValue)
	if l > 0 {
		n += 1 + l + sovDisplayOption(uint64(l))
	}
	l = len(m.BoolFalseValue)
	if l > 0 {
		n += 1 + l + sovDisplayOption(uint64(l))
	}
	if m.Opensea != nil {
		l = m.Opensea.Size()
		n += 1 + l + sovDisplayOption(uint64(l))
	}
	return n
}

func sovDisplayOption(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDisplayOption(x uint64) (n int) {
	return sovDisplayOption(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DisplayOption) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDisplayOption
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DisplayOption: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DisplayOption: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BoolTrueValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDisplayOption
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDisplayOption
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDisplayOption
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BoolTrueValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BoolFalseValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDisplayOption
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDisplayOption
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDisplayOption
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BoolFalseValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Opensea", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDisplayOption
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDisplayOption
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDisplayOption
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Opensea == nil {
				m.Opensea = &OpenseaDisplayOption{}
			}
			if err := m.Opensea.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDisplayOption(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDisplayOption
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDisplayOption(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDisplayOption
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDisplayOption
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDisplayOption
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDisplayOption
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDisplayOption
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDisplayOption
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDisplayOption        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDisplayOption          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDisplayOption = fmt.Errorf("proto: unexpected end of group")
)
