// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: evmsupport/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c1066b9e14fb0e, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c1066b9e14fb0e, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetAddressBindingRequest struct {
	EthAddress    string `protobuf:"bytes,1,opt,name=ethAddress,proto3" json:"ethAddress,omitempty"`
	NativeAddress string `protobuf:"bytes,2,opt,name=nativeAddress,proto3" json:"nativeAddress,omitempty"`
}

func (m *QueryGetAddressBindingRequest) Reset()         { *m = QueryGetAddressBindingRequest{} }
func (m *QueryGetAddressBindingRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAddressBindingRequest) ProtoMessage()    {}
func (*QueryGetAddressBindingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c1066b9e14fb0e, []int{2}
}
func (m *QueryGetAddressBindingRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAddressBindingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAddressBindingRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAddressBindingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAddressBindingRequest.Merge(m, src)
}
func (m *QueryGetAddressBindingRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAddressBindingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAddressBindingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAddressBindingRequest proto.InternalMessageInfo

func (m *QueryGetAddressBindingRequest) GetEthAddress() string {
	if m != nil {
		return m.EthAddress
	}
	return ""
}

func (m *QueryGetAddressBindingRequest) GetNativeAddress() string {
	if m != nil {
		return m.NativeAddress
	}
	return ""
}

type QueryGetAddressBindingResponse struct {
	AddressBinding AddressBinding `protobuf:"bytes,1,opt,name=addressBinding,proto3" json:"addressBinding"`
}

func (m *QueryGetAddressBindingResponse) Reset()         { *m = QueryGetAddressBindingResponse{} }
func (m *QueryGetAddressBindingResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAddressBindingResponse) ProtoMessage()    {}
func (*QueryGetAddressBindingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c1066b9e14fb0e, []int{3}
}
func (m *QueryGetAddressBindingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAddressBindingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAddressBindingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAddressBindingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAddressBindingResponse.Merge(m, src)
}
func (m *QueryGetAddressBindingResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAddressBindingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAddressBindingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAddressBindingResponse proto.InternalMessageInfo

func (m *QueryGetAddressBindingResponse) GetAddressBinding() AddressBinding {
	if m != nil {
		return m.AddressBinding
	}
	return AddressBinding{}
}

type QueryAllAddressBindingRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAddressBindingRequest) Reset()         { *m = QueryAllAddressBindingRequest{} }
func (m *QueryAllAddressBindingRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllAddressBindingRequest) ProtoMessage()    {}
func (*QueryAllAddressBindingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c1066b9e14fb0e, []int{4}
}
func (m *QueryAllAddressBindingRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAddressBindingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAddressBindingRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAddressBindingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAddressBindingRequest.Merge(m, src)
}
func (m *QueryAllAddressBindingRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAddressBindingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAddressBindingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAddressBindingRequest proto.InternalMessageInfo

func (m *QueryAllAddressBindingRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllAddressBindingResponse struct {
	AddressBinding []AddressBinding    `protobuf:"bytes,1,rep,name=addressBinding,proto3" json:"addressBinding"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAddressBindingResponse) Reset()         { *m = QueryAllAddressBindingResponse{} }
func (m *QueryAllAddressBindingResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllAddressBindingResponse) ProtoMessage()    {}
func (*QueryAllAddressBindingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c1066b9e14fb0e, []int{5}
}
func (m *QueryAllAddressBindingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAddressBindingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAddressBindingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAddressBindingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAddressBindingResponse.Merge(m, src)
}
func (m *QueryAllAddressBindingResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAddressBindingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAddressBindingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAddressBindingResponse proto.InternalMessageInfo

func (m *QueryAllAddressBindingResponse) GetAddressBinding() []AddressBinding {
	if m != nil {
		return m.AddressBinding
	}
	return nil
}

func (m *QueryAllAddressBindingResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetActionSignerRequest struct {
	ActorAddress string `protobuf:"bytes,1,opt,name=actorAddress,proto3" json:"actorAddress,omitempty"`
}

func (m *QueryGetActionSignerRequest) Reset()         { *m = QueryGetActionSignerRequest{} }
func (m *QueryGetActionSignerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetActionSignerRequest) ProtoMessage()    {}
func (*QueryGetActionSignerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c1066b9e14fb0e, []int{6}
}
func (m *QueryGetActionSignerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetActionSignerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetActionSignerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetActionSignerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetActionSignerRequest.Merge(m, src)
}
func (m *QueryGetActionSignerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetActionSignerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetActionSignerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetActionSignerRequest proto.InternalMessageInfo

func (m *QueryGetActionSignerRequest) GetActorAddress() string {
	if m != nil {
		return m.ActorAddress
	}
	return ""
}

type QueryGetActionSignerResponse struct {
	ActionSigner ActionSigner `protobuf:"bytes,1,opt,name=actionSigner,proto3" json:"actionSigner"`
}

func (m *QueryGetActionSignerResponse) Reset()         { *m = QueryGetActionSignerResponse{} }
func (m *QueryGetActionSignerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetActionSignerResponse) ProtoMessage()    {}
func (*QueryGetActionSignerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c1066b9e14fb0e, []int{7}
}
func (m *QueryGetActionSignerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetActionSignerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetActionSignerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetActionSignerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetActionSignerResponse.Merge(m, src)
}
func (m *QueryGetActionSignerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetActionSignerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetActionSignerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetActionSignerResponse proto.InternalMessageInfo

func (m *QueryGetActionSignerResponse) GetActionSigner() ActionSigner {
	if m != nil {
		return m.ActionSigner
	}
	return ActionSigner{}
}

type QueryAllActionSignerRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllActionSignerRequest) Reset()         { *m = QueryAllActionSignerRequest{} }
func (m *QueryAllActionSignerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllActionSignerRequest) ProtoMessage()    {}
func (*QueryAllActionSignerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c1066b9e14fb0e, []int{8}
}
func (m *QueryAllActionSignerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllActionSignerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllActionSignerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllActionSignerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllActionSignerRequest.Merge(m, src)
}
func (m *QueryAllActionSignerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllActionSignerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllActionSignerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllActionSignerRequest proto.InternalMessageInfo

func (m *QueryAllActionSignerRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllActionSignerResponse struct {
	ActionSigner []ActionSigner      `protobuf:"bytes,1,rep,name=actionSigner,proto3" json:"actionSigner"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllActionSignerResponse) Reset()         { *m = QueryAllActionSignerResponse{} }
func (m *QueryAllActionSignerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllActionSignerResponse) ProtoMessage()    {}
func (*QueryAllActionSignerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08c1066b9e14fb0e, []int{9}
}
func (m *QueryAllActionSignerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllActionSignerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllActionSignerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllActionSignerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllActionSignerResponse.Merge(m, src)
}
func (m *QueryAllActionSignerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllActionSignerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllActionSignerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllActionSignerResponse proto.InternalMessageInfo

func (m *QueryAllActionSignerResponse) GetActionSigner() []ActionSigner {
	if m != nil {
		return m.ActionSigner
	}
	return nil
}

func (m *QueryAllActionSignerResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "thesixnetwork.sixnft.evmsupport.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "thesixnetwork.sixnft.evmsupport.QueryParamsResponse")
	proto.RegisterType((*QueryGetAddressBindingRequest)(nil), "thesixnetwork.sixnft.evmsupport.QueryGetAddressBindingRequest")
	proto.RegisterType((*QueryGetAddressBindingResponse)(nil), "thesixnetwork.sixnft.evmsupport.QueryGetAddressBindingResponse")
	proto.RegisterType((*QueryAllAddressBindingRequest)(nil), "thesixnetwork.sixnft.evmsupport.QueryAllAddressBindingRequest")
	proto.RegisterType((*QueryAllAddressBindingResponse)(nil), "thesixnetwork.sixnft.evmsupport.QueryAllAddressBindingResponse")
	proto.RegisterType((*QueryGetActionSignerRequest)(nil), "thesixnetwork.sixnft.evmsupport.QueryGetActionSignerRequest")
	proto.RegisterType((*QueryGetActionSignerResponse)(nil), "thesixnetwork.sixnft.evmsupport.QueryGetActionSignerResponse")
	proto.RegisterType((*QueryAllActionSignerRequest)(nil), "thesixnetwork.sixnft.evmsupport.QueryAllActionSignerRequest")
	proto.RegisterType((*QueryAllActionSignerResponse)(nil), "thesixnetwork.sixnft.evmsupport.QueryAllActionSignerResponse")
}

func init() { proto.RegisterFile("evmsupport/query.proto", fileDescriptor_08c1066b9e14fb0e) }

var fileDescriptor_08c1066b9e14fb0e = []byte{
	// 695 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xdf, 0x6a, 0x13, 0x4f,
	0x14, 0xc7, 0x33, 0xed, 0xef, 0x57, 0x74, 0xac, 0x15, 0xc7, 0xa2, 0x12, 0xeb, 0xb6, 0x0c, 0x62,
	0x55, 0x70, 0xa7, 0x4d, 0x45, 0xbc, 0x68, 0x2d, 0x29, 0xd4, 0xde, 0x28, 0xd6, 0x88, 0x08, 0xa2,
	0x94, 0x49, 0x3a, 0x6e, 0x17, 0x93, 0x9d, 0xed, 0xce, 0xa4, 0x7f, 0x28, 0x45, 0xf0, 0xca, 0x4b,
	0xc1, 0x57, 0xf0, 0x41, 0xbc, 0x92, 0x5e, 0x49, 0xd1, 0x1b, 0xaf, 0x44, 0x1a, 0x2f, 0x7c, 0x0c,
	0xd9, 0x99, 0x49, 0xb3, 0xd3, 0x64, 0xdd, 0x24, 0xe4, 0x6e, 0x99, 0x39, 0xe7, 0x7b, 0xce, 0xe7,
	0x9c, 0xb3, 0x67, 0x17, 0x5e, 0x64, 0x5b, 0x35, 0x51, 0x0f, 0x43, 0x1e, 0x49, 0xb2, 0x59, 0x67,
	0xd1, 0xae, 0x1b, 0x46, 0x5c, 0x72, 0x34, 0x29, 0x37, 0x98, 0xf0, 0x77, 0x02, 0x26, 0xb7, 0x79,
	0xf4, 0xc6, 0x8d, 0x1f, 0x5f, 0x4b, 0xb7, 0x65, 0x9c, 0x1f, 0xf7, 0xb8, 0xc7, 0x95, 0x2d, 0x89,
	0x9f, 0xb4, 0x5b, 0x7e, 0xc2, 0xe3, 0xdc, 0xab, 0x32, 0x42, 0x43, 0x9f, 0xd0, 0x20, 0xe0, 0x92,
	0x4a, 0x9f, 0x07, 0xc2, 0xdc, 0xde, 0xaa, 0x70, 0x51, 0xe3, 0x82, 0x94, 0xa9, 0x60, 0x3a, 0x1a,
	0xd9, 0x9a, 0x2d, 0x33, 0x49, 0x67, 0x49, 0x48, 0x3d, 0x3f, 0x50, 0xc6, 0xc6, 0xf6, 0x52, 0x22,
	0xb1, 0x90, 0x46, 0xb4, 0xd6, 0x14, 0x99, 0x4a, 0x5c, 0xd0, 0xf5, 0xf5, 0x88, 0x09, 0xb1, 0x56,
	0xf6, 0x83, 0x75, 0x3f, 0xf0, 0x8c, 0x85, 0x93, 0xb4, 0xa8, 0xc4, 0x9a, 0x6b, 0xc2, 0xf7, 0x02,
	0x16, 0xe9, 0x7b, 0x3c, 0x0e, 0xd1, 0x93, 0x38, 0xf8, 0xaa, 0x92, 0x2d, 0xb1, 0xcd, 0x3a, 0x13,
	0x12, 0xbf, 0x84, 0x17, 0xac, 0x53, 0x11, 0xf2, 0x40, 0x30, 0xb4, 0x0c, 0x47, 0x74, 0xf8, 0xcb,
	0x60, 0x0a, 0xdc, 0x38, 0x53, 0x98, 0x76, 0x33, 0x2a, 0xe3, 0x6a, 0x81, 0xa5, 0xff, 0x0e, 0x7e,
	0x4e, 0xe6, 0x4a, 0xc6, 0x19, 0x33, 0x78, 0x55, 0xa9, 0xaf, 0x30, 0x59, 0xd4, 0x49, 0x2f, 0xe9,
	0x9c, 0x4d, 0x78, 0xe4, 0x40, 0xc8, 0xe4, 0x86, 0xb9, 0x53, 0xb1, 0x4e, 0x97, 0x12, 0x27, 0xe8,
	0x1a, 0x3c, 0x1b, 0xd7, 0x67, 0x8b, 0x35, 0x4d, 0x86, 0x94, 0x89, 0x7d, 0x88, 0xdf, 0x42, 0x27,
	0x2d, 0x8c, 0xe1, 0x79, 0x05, 0xc7, 0xa8, 0x75, 0x63, 0xb8, 0x48, 0x26, 0x97, 0x2d, 0x68, 0xf8,
	0x4e, 0x88, 0x61, 0xcf, 0x70, 0x16, 0xab, 0xd5, 0xce, 0x9c, 0x0f, 0x20, 0x6c, 0xf5, 0xda, 0xc4,
	0xbe, 0xee, 0xea, 0xc1, 0x70, 0xe3, 0xc1, 0x70, 0xf5, 0x18, 0x9a, 0xc1, 0x70, 0x57, 0xa9, 0xc7,
	0x8c, 0x6f, 0x29, 0xe1, 0x89, 0x0f, 0x80, 0x41, 0xed, 0x10, 0xe9, 0x1f, 0xa8, 0xc3, 0x03, 0x43,
	0x45, 0x2b, 0x16, 0xc9, 0x90, 0x99, 0x8e, 0x2c, 0x12, 0x9d, 0x9b, 0x85, 0x52, 0x84, 0x57, 0x8e,
	0x9b, 0xa6, 0xc6, 0xf5, 0xa9, 0x9a, 0xd6, 0x66, 0xc5, 0x30, 0x1c, 0xa5, 0x15, 0xc9, 0x23, 0x7b,
	0x36, 0xac, 0x33, 0xbc, 0x0d, 0x27, 0x3a, 0x4b, 0x98, 0x52, 0x3c, 0x57, 0x1a, 0xc7, 0xe7, 0xa6,
	0xee, 0xb7, 0xb3, 0x0b, 0x91, 0x70, 0x32, 0x65, 0xb0, 0x84, 0x30, 0x33, 0xb9, 0xc7, 0x5d, 0xe8,
	0x90, 0xfb, 0xa0, 0xba, 0xfd, 0x19, 0x18, 0xc0, 0xb6, 0x38, 0xa9, 0x80, 0xc3, 0x03, 0x01, 0x1c,
	0x58, 0x97, 0x0b, 0xef, 0x4f, 0xc1, 0xff, 0x15, 0x02, 0xfa, 0x04, 0xe0, 0x88, 0x5e, 0x12, 0x68,
	0x2e, 0x33, 0xc1, 0xf6, 0x4d, 0x95, 0xbf, 0xd3, 0x9b, 0x93, 0xce, 0x05, 0x93, 0x77, 0xdf, 0x7f,
	0x7f, 0x1c, 0xba, 0x89, 0xa6, 0x89, 0xe5, 0x4d, 0xb4, 0x37, 0x69, 0x5b, 0xb7, 0xe8, 0x0f, 0x80,
	0x63, 0xf6, 0x8b, 0x80, 0xee, 0x77, 0x17, 0x39, 0x6d, 0xc9, 0xe5, 0x17, 0xfb, 0xf6, 0x37, 0x10,
	0xcf, 0x14, 0xc4, 0x63, 0xf4, 0x28, 0x13, 0xe2, 0xc4, 0xa7, 0x81, 0xec, 0xb5, 0x76, 0xe9, 0x3e,
	0xd9, 0xb3, 0xb6, 0xe6, 0x3e, 0xfa, 0x0a, 0xe0, 0x79, 0x3b, 0x62, 0xb1, 0x5a, 0xed, 0x96, 0x36,
	0x6d, 0xd5, 0x75, 0x4b, 0x9b, 0xba, 0xc0, 0xf0, 0x3d, 0x45, 0x5b, 0x40, 0x33, 0xbd, 0xd2, 0xa2,
	0x6f, 0x00, 0x8e, 0x26, 0x47, 0x1b, 0xcd, 0x77, 0x5f, 0xf9, 0xf6, 0xd7, 0x38, 0xbf, 0xd0, 0xa7,
	0xb7, 0xe1, 0x58, 0x56, 0x1c, 0x8b, 0x68, 0x21, 0x9b, 0x23, 0xf9, 0xb9, 0x26, 0x7b, 0xc9, 0x1d,
	0xb7, 0x8f, 0xbe, 0x00, 0x78, 0x2e, 0xa9, 0x1f, 0xf7, 0x68, 0xbe, 0xfb, 0x1a, 0xf7, 0xcf, 0x95,
	0xb2, 0x74, 0xf0, 0x5d, 0xc5, 0x35, 0x83, 0xdc, 0xde, 0xb8, 0x96, 0x1e, 0x1e, 0x1c, 0x39, 0xe0,
	0xf0, 0xc8, 0x01, 0xbf, 0x8e, 0x1c, 0xf0, 0xa1, 0xe1, 0xe4, 0x0e, 0x1b, 0x4e, 0xee, 0x47, 0xc3,
	0xc9, 0xbd, 0x28, 0x78, 0xbe, 0xdc, 0xa8, 0x97, 0xdd, 0x0a, 0xaf, 0x75, 0xd6, 0xdc, 0x49, 0xaa,
	0xca, 0xdd, 0x90, 0x89, 0xf2, 0x88, 0xfa, 0xab, 0x99, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xbf,
	0xde, 0x7a, 0xe2, 0xcb, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a AddressBinding by index.
	AddressBinding(ctx context.Context, in *QueryGetAddressBindingRequest, opts ...grpc.CallOption) (*QueryGetAddressBindingResponse, error)
	// Queries a list of AddressBinding items.
	AddressBindingAll(ctx context.Context, in *QueryAllAddressBindingRequest, opts ...grpc.CallOption) (*QueryAllAddressBindingResponse, error)
	// Queries a ActionSigner by index.
	ActionSigner(ctx context.Context, in *QueryGetActionSignerRequest, opts ...grpc.CallOption) (*QueryGetActionSignerResponse, error)
	// Queries a list of ActionSigner items.
	ActionSignerAll(ctx context.Context, in *QueryAllActionSignerRequest, opts ...grpc.CallOption) (*QueryAllActionSignerResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/thesixnetwork.sixnft.evmsupport.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AddressBinding(ctx context.Context, in *QueryGetAddressBindingRequest, opts ...grpc.CallOption) (*QueryGetAddressBindingResponse, error) {
	out := new(QueryGetAddressBindingResponse)
	err := c.cc.Invoke(ctx, "/thesixnetwork.sixnft.evmsupport.Query/AddressBinding", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AddressBindingAll(ctx context.Context, in *QueryAllAddressBindingRequest, opts ...grpc.CallOption) (*QueryAllAddressBindingResponse, error) {
	out := new(QueryAllAddressBindingResponse)
	err := c.cc.Invoke(ctx, "/thesixnetwork.sixnft.evmsupport.Query/AddressBindingAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ActionSigner(ctx context.Context, in *QueryGetActionSignerRequest, opts ...grpc.CallOption) (*QueryGetActionSignerResponse, error) {
	out := new(QueryGetActionSignerResponse)
	err := c.cc.Invoke(ctx, "/thesixnetwork.sixnft.evmsupport.Query/ActionSigner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ActionSignerAll(ctx context.Context, in *QueryAllActionSignerRequest, opts ...grpc.CallOption) (*QueryAllActionSignerResponse, error) {
	out := new(QueryAllActionSignerResponse)
	err := c.cc.Invoke(ctx, "/thesixnetwork.sixnft.evmsupport.Query/ActionSignerAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a AddressBinding by index.
	AddressBinding(context.Context, *QueryGetAddressBindingRequest) (*QueryGetAddressBindingResponse, error)
	// Queries a list of AddressBinding items.
	AddressBindingAll(context.Context, *QueryAllAddressBindingRequest) (*QueryAllAddressBindingResponse, error)
	// Queries a ActionSigner by index.
	ActionSigner(context.Context, *QueryGetActionSignerRequest) (*QueryGetActionSignerResponse, error)
	// Queries a list of ActionSigner items.
	ActionSignerAll(context.Context, *QueryAllActionSignerRequest) (*QueryAllActionSignerResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) AddressBinding(ctx context.Context, req *QueryGetAddressBindingRequest) (*QueryGetAddressBindingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddressBinding not implemented")
}
func (*UnimplementedQueryServer) AddressBindingAll(ctx context.Context, req *QueryAllAddressBindingRequest) (*QueryAllAddressBindingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddressBindingAll not implemented")
}
func (*UnimplementedQueryServer) ActionSigner(ctx context.Context, req *QueryGetActionSignerRequest) (*QueryGetActionSignerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActionSigner not implemented")
}
func (*UnimplementedQueryServer) ActionSignerAll(ctx context.Context, req *QueryAllActionSignerRequest) (*QueryAllActionSignerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActionSignerAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thesixnetwork.sixnft.evmsupport.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AddressBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAddressBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AddressBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thesixnetwork.sixnft.evmsupport.Query/AddressBinding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AddressBinding(ctx, req.(*QueryGetAddressBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AddressBindingAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllAddressBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AddressBindingAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thesixnetwork.sixnft.evmsupport.Query/AddressBindingAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AddressBindingAll(ctx, req.(*QueryAllAddressBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ActionSigner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetActionSignerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ActionSigner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thesixnetwork.sixnft.evmsupport.Query/ActionSigner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ActionSigner(ctx, req.(*QueryGetActionSignerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ActionSignerAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllActionSignerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ActionSignerAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thesixnetwork.sixnft.evmsupport.Query/ActionSignerAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ActionSignerAll(ctx, req.(*QueryAllActionSignerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "thesixnetwork.sixnft.evmsupport.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "AddressBinding",
			Handler:    _Query_AddressBinding_Handler,
		},
		{
			MethodName: "AddressBindingAll",
			Handler:    _Query_AddressBindingAll_Handler,
		},
		{
			MethodName: "ActionSigner",
			Handler:    _Query_ActionSigner_Handler,
		},
		{
			MethodName: "ActionSignerAll",
			Handler:    _Query_ActionSignerAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evmsupport/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetAddressBindingRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAddressBindingRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAddressBindingRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NativeAddress) > 0 {
		i -= len(m.NativeAddress)
		copy(dAtA[i:], m.NativeAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.NativeAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.EthAddress) > 0 {
		i -= len(m.EthAddress)
		copy(dAtA[i:], m.EthAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.EthAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAddressBindingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAddressBindingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAddressBindingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.AddressBinding.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllAddressBindingRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAddressBindingRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAddressBindingRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllAddressBindingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAddressBindingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAddressBindingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.AddressBinding) > 0 {
		for iNdEx := len(m.AddressBinding) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AddressBinding[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetActionSignerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetActionSignerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetActionSignerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ActorAddress) > 0 {
		i -= len(m.ActorAddress)
		copy(dAtA[i:], m.ActorAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ActorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetActionSignerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetActionSignerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetActionSignerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ActionSigner.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllActionSignerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllActionSignerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllActionSignerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllActionSignerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllActionSignerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllActionSignerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ActionSigner) > 0 {
		for iNdEx := len(m.ActionSigner) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ActionSigner[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetAddressBindingRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EthAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.NativeAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAddressBindingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.AddressBinding.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllAddressBindingRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllAddressBindingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AddressBinding) > 0 {
		for _, e := range m.AddressBinding {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetActionSignerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ActorAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetActionSignerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ActionSigner.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllActionSignerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllActionSignerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ActionSigner) > 0 {
		for _, e := range m.ActionSigner {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAddressBindingRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAddressBindingRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAddressBindingRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EthAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NativeAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NativeAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAddressBindingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAddressBindingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAddressBindingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressBinding", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AddressBinding.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAddressBindingRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAddressBindingRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAddressBindingRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAddressBindingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAddressBindingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAddressBindingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressBinding", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddressBinding = append(m.AddressBinding, AddressBinding{})
			if err := m.AddressBinding[len(m.AddressBinding)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetActionSignerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetActionSignerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetActionSignerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetActionSignerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetActionSignerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetActionSignerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionSigner", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ActionSigner.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllActionSignerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllActionSignerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllActionSignerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllActionSignerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllActionSignerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllActionSignerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionSigner", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActionSigner = append(m.ActionSigner, ActionSigner{})
			if err := m.ActionSigner[len(m.ActionSigner)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
